version: '3.8'

services:
  postgres:
    container_name: pgdb_virtual_shops
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
    networks:
      - virtual_shops
    restart: unless-stopped

networks:
  virtual_shops:
    driver: bridge

volumes:
  postgres:
